name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GCP
        uses: "google-github-actions/auth@v3"
        with:
          project_id: "cm-lubinski-info"
          workload_identity_provider: "projects/156088670038/locations/global/workloadIdentityPools/github/providers/more-vanity"
      - uses: "google-github-actions/setup-gcloud@v3"

      - name: Build container and site
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/cmc333333/more-vanity-devcontainer
          runCmd: |
            npm install
            rm -rf dist
            npm run build

      - name: Copy to bucket
        run: gsutil -m rsync -r -d dist gs://cm-lubinski-info-website/
