on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/cmc333333/more-vanity-devcontainer
          runCmd: |
            npm install
            npm run build

      - run: ls dist
